var adimlar = [
    "o",
    "o!",
    "o!r",
    "o!re",
    "o!res",
    "o!resi",
    "o!resim",
    "o!resim ",
    "o!resim e",
    "o!resim el",
    "o!resim elm",
    "o!resim elma",
    "o!resim elma",
    "o!resim elma",
    "o!resim elma",
    "o!resim elma",
    "o!resim elm",
    "o!resim el",
    "o!resim e",
    "o!resim ",
    "o!resim ",
    "o!resi",
    "o!res",
    "o!re",
    "o!r",
    "o!",
    "o!o",
    "o!oy",
    "o!oyn",
    "o!oyna",
    "o!oynat",
    "o!oynat ",
    "o!oynat r",
    "o!oynat ra",
    "o!oynat rap",
    "o!oynat rap ",
    "o!oynat rap g",
    "o!oynat rap go",
    "o!oynat rap god",
    "o!oynat rap god",
    "o!oynat rap god",
    "o!oynat rap god",
    "o!oynat rap god",
    "o!oynat rap go",
    "o!oynat rap g",
    "o!oynat rap ",
    "o!oynat rap",
    "o!oynat ra",
    "o!oynat r",
    "o!oynat ",
    "o!oynat",
    "o!oyna",
    "o!oyn",
    "o!oy",
    "o!o",
    "o!",
    "o!e",
    "o!ea",
    "o!ear",
    "o!earr",
    "o!earra",
    "o!earrap",
    "o!earrape",
    "o!earrape",
    "o!earrape",
    "o!earrape",
    "o!earrape",
    "o!earrap",
    "o!earra",
    "o!earr",
    "o!ear",
    "o!ea",
    "o!e",
    "o!",
    "o!e",
    "o!ek",
    "o!ekş",
    "o!ekşi",
    "o!ekşi ",
    "o!ekşi p",
    "o!ekşi pe",
    "o!ekşi pen",
    "o!ekşi pena",
    "o!ekşi pena",
    "o!ekşi pena",
    "o!ekşi pena",
    "o!ekşi pena",
    "o!ekşi pen",
    "o!ekşi pe",
    "o!ekşi p",
    "o!ekşi ",
    "o!ekşi",
    "o!ekş",
    "o!ek",
    "o!e",
    "o!",
    "o!o",
    "o!oy",
    "o!oyl",
    "o!oyla",
    "o!oylam",
    "o!oylama",
    "o!oylama",
    "o!oylama",
    "o!oylama",
    "o!oylama",
    "o!oylam",
    "o!oyla",
    "o!oyl",
    "o!oy",
    "o!o",
    "o!",
    "o!y",
    "o!ya",
    "o!yaz",
    "o!yazı",
    "o!yazıt",
    "o!yazıtu",
    "o!yazıtur",
    "o!yazıtura",
    "o!yazıtura",
    "o!yazıtura",
    "o!yazıtura",
    "o!yazıtura",
    "o!yazıtur",
    "o!yazıtu",
    "o!yazıt",
    "o!yazı",
    "o!yaz",
    "o!ya",
    "o!y",
    "o!",
    "o!y",
    "o!yo",
    "o!you",
    "o!yout",
    "o!youtu",
    "o!youtub",
    "o!youtube",
    "o!youtube",
    "o!youtube",
    "o!youtube",
    "o!youtube",
    "o!youtub",
    "o!youtu",
    "o!yout",
    "o!you",
    "o!yo",
    "o!y",
    "o!",
    "o!k",
    "o!ku",
    "o!kur",
    "o!kur",
    "o!kur",
    "o!kur",
    "o!kur",
    "o!ku",
    "o!k",
    "o!",
    "o!c",
    "o!co",
    "o!cou",
    "o!coun",
    "o!count",
    "o!counte",
    "o!counter",
    "o!counter ",
    "o!counter g",
    "o!counter ga",
    "o!counter gar",
    "o!counter gare",
    "o!counter garen",
    "o!counter garen",
    "o!counter garen",
    "o!counter garen",
    "o!counter garen",
    "o!counter gare",
    "o!counter gar",
    "o!counter ga",
    "o!counter g",
    "o!counter ",
    "o!counter",
    "o!counte",
    "o!count",
    "o!coun",
    "o!cou",
    "o!co",
    "o!c",
    "o!",
    "o!h",
    "o!ha",
    "o!hav",
    "o!hava",
    "o!hava ",
    "o!hava  İ",
    "o!hava İs",
    "o!hava İst",
    "o!hava İsta",
    "o!hava İstan",
    "o!hava İstanb",
    "o!hava İstanbu",
    "o!hava İstanbul",
    "o!hava İstanbul",
    "o!hava İstanbul",
    "o!hava İstanbul",
    "o!hava İstanbul",
    "o!hava İstanbu",
    "o!hava İstanb",
    "o!hava İstan",
    "o!hava İsta",
    "o!hava İst",
    "o!hava İs",
    "o!hava İ",
    "o!hava ",
    "o!hava",
    "o!hav",
    "o!ha",
    "o!h",
    "o!",
    "o!y",
    "o!ya",
    "o!yaz",
    "o!yazm",
    "o!yazma",
    "o!yazmay",
    "o!yazmaya",
    "o!yazmayar",
    "o!yazmayarı",
    "o!yazmayarış",
    "o!yazmayarışı",
    "o!yazmayarışı",
    "o!yazmayarışı",
    "o!yazmayarışı",
    "o!yazmayarışı",
    "o!yazmayarış",
    "o!yazmayarı",
    "o!yazmayar",
    "o!yazmaya",
    "o!yazmay",
    "o!yazma",
    "o!yazm",
    "o!yaz",
    "o!ya",
    "o!y",
    "o!" 
]
var x = 0;
var element = document.getElementById("command");
setInterval(() => {
    element.innerText = adimlar[x];
    if (x == adimlar.length - 1) {
        x = 0;
    } else {
        x += 1;
    }
}, 100)